### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by hen** [goneall/spdx-maven-plugin#1]
Hi Gary,

Could you an example of how to hook this in to a project? I've seen you show one on screen in a talk, presumably that would work :) Currently there's nothing on how to apply this to a project.

**Comment by goneall** [comment]
Will do - I'll add some documentation this weekend or early next week.

**Comment by goneall** [comment]
Hi Henri,

I updated the readme file to be a bit more descriptive and added an example from the SPDX tools.  There is more documentation I should probably do, but hopefully this will address the short term need.  Please open an additional issue if you see anything more that would help document.

FYI - I also moved all of the issues out of the readme file and entered them in as issues in Git.
